change password button is disabled
fossasia/susi_firefoxbot pull request #193
Opened 2019-05-18 05:57 UTC by Mishra121

Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

#### Changes proposed in this pull request:
- 

#### Demo Link: 
[Add here the link where your changes can be seen]

#### Screenshots for the change:

2019-05-18 10:31 UTC, samagragupta reviewed
Please screenshot or gif and also issue number in the description.

2019-05-18 10:55 UTC, Mishra121 commented
pull request description updated.

2019-05-18 12:41 UTC, samagragupta approved these changes

2019-06-05 07:53 UTC, tstreamDOTh requested changes

2019-06-05 07:53 UTC, tstreamDOTh commented on src/scripts/options.js
> +var changepasswordsubmitButton = document.getElementById("changepasswordsubmit");
Declare the variables at the top

2020-06-30 07:24 UTC, tstreamDOTh commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/scripts/options.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/tstreamDOTh/susi_firefoxbot/pullRequest?prid=5777456&bid=18914679)

2022-07-19 14:55 UTC, closed without merging